import Head from 'next/head'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'

export default function Home(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {JSON.stringify(props.json)}
      </main>
    </>
  )
}

export const getServerSideProps = (async () => {
  // サーバーサイドから実行される GraphQL リクエストを雑に書いておく
  const res = await fetch('http://localhost:3000/api/graphql', {
    method: 'POST',
    credentials: 'include',
    headers: { Accept: 'application/json', 'Content-Type': 'application/json', },
    body: JSON.stringify({ query: 'query HomeQuery {\n hello\n }', variables: {} }),
  })
  const json = await res.json()
  return { props: { json } }
}) satisfies GetServerSideProps
